<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE blueColumn [
  <!ELEMENT blueColumn (column,NeuronTypes,Seeds?,SynapsesProperties,SynapsesClassification,DendriticMorphologyProbabilities,TouchRules,InterBoutonInterval?)>
  <!ELEMENT column (layer*)>
  <!ATTLIST column id CDATA #REQUIRED x CDATA #REQUIRED z CDATA #REQUIRED>
  <!ELEMENT layer (#PCDATA)>
  <!ATTLIST layer	id CDATA #REQUIRED height CDATA #REQUIRED>
  <!ELEMENT NeuronTypes (Layer*)>
  <!ATTLIST NeuronTypes totalNeurons CDATA #REQUIRED miniColumns CDATA #REQUIRED IntExtendedMinicolumnRadious CDATA #REQUIRED>
  <!ELEMENT Layer (StructuralType*)>
  <!ATTLIST Layer id CDATA #REQUIRED percentage CDATA #REQUIRED>
  <!ELEMENT StructuralType (ElectroType*)>
  <!ATTLIST StructuralType id CDATA #REQUIRED percentage CDATA #REQUIRED sigma CDATA #REQUIRED exclusionRadius CDATA #REQUIRED mClass CDATA #REQUIRED sClass CDATA #REQUIRED spineLength CDATA #REQUIRED>
  <!ELEMENT ElectroType (#PCDATA)>
  <!ATTLIST ElectroType id CDATA #REQUIRED percentage CDATA #REQUIRED>
  <!ELEMENT Seeds (#PCDATA)>
  <!ATTLIST Seeds recipeSeed CDATA #IMPLIED columnSeed CDATA #IMPLIED synapseSeed CDATA #IMPLIED>
  <!ELEMENT InterBoutonInterval (#PCDATA)>
  <!ATTLIST InterBoutonInterval minDistance CDATA #IMPLIED maxDistance CDATA #IMPLIED regionGap CDATA #IMPLIED>
  <!ELEMENT SynapsesProperties (synapse*)>
  <!ELEMENT synapse (#PCDATA)>
  <!ATTLIST synapse id1 CDATA #REQUIRED id2 CDATA #REQUIRED id3 CDATA #REQUIRED id4 CDATA #REQUIRED GAB1 CDATA #REQUIRED GAB2 CDATA #REQUIRED>
  <!ELEMENT SynapsesClassification (class*)>
  <!ELEMENT class (#PCDATA)>
  <!ATTLIST class id CDATA #REQUIRED gsyn CDATA #REQUIRED gsynVar CDATA #REQUIRED nsyn CDATA #REQUIRED nsynVar CDATA #REQUIRED dtc CDATA #REQUIRED dtcVar CDATA #REQUIRED u CDATA #REQUIRED uVar CDATA #REQUIRED d CDATA #REQUIRED dVar CDATA #REQUIRED f CDATA #REQUIRED fVar CDATA #REQUIRED ase CDATA #REQUIRED>
  <!ELEMENT ConnectionRules (class*)>  
  <!ELEMENT TouchRules (class*)>
  <!ENTITY connectivityRecipe SYSTEM "builderConnectivityRecipeAllPathways.xml">
]>


<blueColumn>
	<NeuronTypes totalNeurons="31346" miniColumns="310" IntExtendedMinicolumnRadious="23">
		<Layer id="1" percentage="10.0">

		  <StructuralType id="L1_DAC" percentage="100" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-35">
		    <ElectroType id="bNAC" percentage="33.33"/>
		    <ElectroType id="cNAC" percentage="66.67"/>
		  </StructuralType>
		</Layer>
		<Layer id="2" percentage="90.0">
			<StructuralType id="L23_PC" percentage="50" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100" />
			</StructuralType>

			<StructuralType id="L23_MC" percentage="50" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-120">
			  <ElectroType id="bAC" percentage="2.44"/>
			</StructuralType>
			<StructuralType id="L23_BTC" percentage="50" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-15">
			  <ElectroType id="bAC" percentage="13.89"/>
			  <ElectroType id="bIR" percentage="5.56"/>
			  <ElectroType id="bNAC" percentage="22.22"/>
			  <ElectroType id="cACint" percentage="41.67"/>
			  <ElectroType id="cNAC" percentage="16.67"/>
			</StructuralType>
		</Layer>
	</NeuronTypes>

	&connectivityRecipe;

</blueColumn>

